### ISSUE TITLE
Lootmaster loot assigning is not detected.

### ISSUE THREAD

**Issue by Blazewardog** [kalilistic/Kapture#22]
Lootmaster loot assigning never shows the drops as "won"
Log line is in the format of "[Character/You] claim the [Loot]."

**Comment by kalilistic** [comment]
Thanks for reporting. I should be able to add this tomorrow.

**Comment by kalilistic** [comment]
This should now be fixed in the beta release. You can download the beta release by enabling "check for beta versions" or downloading directly from the releases page. Let me know if looks OK.

Adding a few more notes for posterity's sake...
- Found issue in both English/Japanese.
- German/French seem to use same wording as "normal" obtain item messages.

Sample Messages
- You claim the plundered haubergeon.
- Combatant One claims the plundered haubergeon.
- Du hast den zerbrochenen Stock erhalten.
- Combatant One hat das ätherische Wolfs-Halsband erhalten.
- Vous obtenez l'armure d'écailles rouillée.
- Combatant One obtient l'espadon en mithril éthéréen.
- Combatant Oneにエーテリアル・ウールサッシュが分配されました。

**Comment by kalilistic** [comment]
Closing but feel free to re-open if you still have this issue. Thanks!
